<?php

// $Id: dashboard.info,v 1.4 2011/07/04 13:25:57 dries Exp $

/**
 * Implementation of hook_init
 */
function dashboard_init() {
}

/**
 * Implements hook_help().
 */
function dashboard_help($path, $arg) {
    switch ($path) {
        case 'admin/help#dashboard':
            $output = '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('主页模块');
            return $output;
    }
}

/**
 * Implements hook_permission().
 */
function dashboard_permission() {
    return array(
        'dashboard' => array(
            'title' => t('主页'),
        ),
    );
}

function dashboard_menu() {
    $items = array();
    $items['dashboard'] = array(
        'title' => t('主页'),
        'page callback' => 'dashboard_call_back',
        'access arguments' => array('dashboard'),
        'weight' => -47,
        'type' => MENU_CALLBACK,
    );

     $items['login/%'] = array(
        'title' => t('主页'),
        'page callback' => 'login_call_back',
        'page arguments' => array(1),
        'access arguments' => array('dashboard'),
        'weight' => -47,
        'type' => MENU_CALLBACK,
    );

     $items['login'] = array(
        'title' => t('主页'),
        'page callback' => 'login_call_back_no_name',
        'access arguments' => array('dashboard'),
        'weight' => -47,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dashboard_call_back() {
    global $user;
    if($user->uid == 0)
        drupal_goto('user/login');
    $pageContent = '';
    return $pageContent;
}

function login_call_back_no_name(){
    session_destroy();
    drupal_goto('user/login');
}

function login_call_back($login_name){
//    session_destroy();
    $account = user_load_by_name($login_name);
    if(!empty($account)){
         global $user;
        $user = user_load($account->uid);
        user_login_finalize();
        drupal_goto('dashboard');
    } else {
        echo 'There is no such user in system!';
    }
   
}


function message_display(){
    $output = "";
    $messages = drupal_get_messages();
    if ($messages){
        foreach ($messages as $status => $msgs){
            $output .= "<div class='messages $status'>";
            $output .= "    <ul>";
             foreach ($msgs as $msg){
                $output .= "    <li>";
                $output .=          $msg;
                $output .= "    </li>";
             }
            $output .= "    </ul>";
            $output .= "</div>";
        }
    }
        return $output;
}