<?php

// $Id: bills_ticket.info,v 1.4 2011/07/04 13:25:57 dries Exp $

/**
 * Implementation of hook_init
 */
function bills_ticket_init() {
}

/**
 * Implements hook_help().
 */
function bills_ticket_help($path, $arg) {
    switch ($path) {
        case 'admin/help#bills_ticket':
            $output = '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('开票');
            return $output;
    }
}

/**
 * Implements hook_permission().
 */
function bills_ticket_permission() {
    return array(
        'bills_ticket' => array(
            'title' => t('开票'),
        ),
    );
}

function bills_ticket_menu() {
    $items = array();
    $items['billsticket'] = array(
        'title' => t('开票'),
        'page callback' => 'bills_ticket_call_back',
        'access arguments' => array('bills_ticket'),
        'weight' => 30,
    );

    $items['billsticketavailablenumber'] = array(
        'page callback' => 'drupal_get_form',
        'page callback' => 'bills_ticket_get_available_number',
        'access arguments' => array('bills_ticket'),
        'type' => MENU_CALLBACK,
    );
    
    $items['billsticketsubmit'] = array(
        'page callback' => 'drupal_get_form',
        'access arguments' => array('bills_ticket'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function bills_ticket_call_back() {
  $pagecontent = "<h1><strong>开票</strong></h1>";
  $pagecontent .= message_display();
  $pagecontent .= theme('bills_ticket');
  return $pagecontent;
}

function bills_ticket_get_available_number(){
    $type = $_POST['type'];
    $query = db_select('bills')->fields('bills',array('billsno'))
            ->condition('type', $type,'=')
            ->condition('status', '可用','=')
            ->range(0,1)
            ->orderBy('billsno');
    $result = $query->execute();
    $billsnos = $result->fetchAssoc();
    if($billsnos && count($billsnos)>0)
        echo '<span class="availableno">'.$billsnos[billsno].'</span>';
    else
        echo '<span class="unavailableno">该票据类型无可用编号</span>';
}

function bills_ticket_theme() {
    return array(
        'bills_ticket' => array(
            'template' => 'bills_ticket',
        ),
    );
}

function bills_ticket_out(){
    
}