<?php

// $Id: bills_apply.info,v 1.4 2011/07/04 13:25:57 dries Exp $

/**
 * Implementation of hook_init
 */
function bills_apply_init() {
    drupal_add_css(drupal_get_path('module', 'bills_apply') . '/bills_apply.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));
}

/**
 * Implements hook_help().
 */
function bills_apply_help($path, $arg) {
    switch ($path) {
        case 'admin/help#bills_apply':
            $output = '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('票据申请');
            return $output;
    }
}

/**
 * Implements hook_permission().
 */
function bills_apply_permission() {
    return array(
        'bills_apply' => array(
            'title' => t('票据申请'),
        ),
    );
}

function bills_apply_menu() {
    $items = array();
    $items['billsapply'] = array(
        'title' => t('票据申请'),
        'page callback' => 'bills_apply',
        'access arguments' => array('bills_apply'),
        'weight' => 10,
    );

    $items['billsapplysubmit'] = array(
        'title' => t('票据申请'),
        'page callback' => 'bills_apply_submit',
        'access arguments' => array('bills_apply'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}
function bills_apply($form, &$form_state) {
    return theme('bills_apply');
}

function bills_apply_theme() {
    return array(
        'bills_apply' => array(
            'template' => 'bills_apply_form',
        ),
    );
}

function bills_apply_submit(){
    $unit = $_POST['unit'];
    $amount = $_POST['amount'];
    $alloc_data = $_POST['alloc_data'];
    dd($unit);
    dd($amount);
    dd($alloc_data);
}
