<?php

// $Id: bills_handin.info,v 1.4 2011/07/04 13:25:57 dries Exp $

/**
 * Implementation of hook_init
 */
function bills_handin_init() {

}

/**
 * Implements hook_help().
 */
function bills_handin_help($path, $arg) {
    switch ($path) {
        case 'admin/help#bills_handin':
            $output = '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('票据缴销');
            return $output;
    }
}

/**
 * Implements hook_permission().
 */
function bills_handin_permission() {
    return array(
        'bills_handin' => array(
            'title' => t('票据缴销'),
        ),
    );
}

function bills_handin_menu() {
    $items = array();
    $items['billshandin'] = array(
        'title' => t('票据缴销'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bills_handin_form'),
        'access arguments' => array('bills_handin'),
        'file' => 'bills_handin.inc',
        'access arguments' => array('bills_handin'),
        'weight' => 0,
    );

    $items['billshandincheck'] = array(
        'title' => t('票据缴销确认'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bills_handin_check_form'),
        'access arguments' => array('bills_handin'),
        'file' => 'bills_handin_check.inc',
        'access arguments' => array('bills_handin'),
        'weight' => 0,
    );

    return $items;
}
